
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 19 10:55:59 CET 2026
//----------------------------------------------------

package lab1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 17;
  public static final int PLUS = 10;
  public static final int RBRACE = 16;
  public static final int RPAREN = 14;
  public static final int INT = 5;
  public static final int CHAR = 6;
  public static final int COLON = 19;
  public static final int LPAREN = 13;
  public static final int LBRACE = 15;
  public static final int ID = 2;
  public static final int COMMA = 18;
  public static final int FLOAT = 7;
  public static final int EOF = 0;
  public static final int WHEN = 9;
  public static final int MAIN = 4;
  public static final int MINUS = 11;
  public static final int CONST = 3;
  public static final int CASE = 8;
  public static final int error = 1;
  public static final int ASSIGN = 12;
}

