
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 19 09:45:39 CET 2026
//----------------------------------------------------

package lab1;

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Mon Jan 19 09:45:39 CET 2026
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\050\000\002\002\004\000\002\003\006\000\002\003" +
    "\007\000\002\003\005\000\002\003\004\000\002\004\006" +
    "\000\002\005\004\000\002\005\005\000\002\005\002\000" +
    "\002\006\005\000\002\006\005\000\002\010\003\000\002" +
    "\010\005\000\002\010\005\000\002\007\003\000\002\007" +
    "\003\000\002\007\003\000\002\011\004\000\002\011\003" +
    "\000\002\012\003\000\002\012\006\000\002\012\006\000" +
    "\002\012\006\000\002\012\003\000\002\013\011\000\002" +
    "\013\011\000\002\013\007\000\002\014\004\000\002\014" +
    "\003\000\002\015\006\000\002\015\006\000\002\015\006" +
    "\000\002\016\005\000\002\016\003\000\002\020\003\000" +
    "\002\020\003\000\002\017\003\000\002\017\003\000\002" +
    "\017\005\000\002\017\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\006\003\005\004\006\001\002\000\004\002" +
    "\122\001\002\000\004\021\014\001\002\000\006\003\007" +
    "\017\010\001\002\000\004\021\014\001\002\000\006\003" +
    "\012\020\011\001\002\000\004\021\014\001\002\000\004" +
    "\020\013\001\002\000\004\021\014\001\002\000\020\003" +
    "\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\012\ufff9\021\ufff9" +
    "\001\002\000\004\002\uffff\001\002\000\020\003\026\005" +
    "\020\006\032\007\031\010\030\012\025\021\014\001\002" +
    "\000\004\012\110\001\002\000\004\012\ufff3\001\002\000" +
    "\014\010\uffea\011\uffea\012\uffea\021\uffea\022\uffea\001\002" +
    "\000\012\010\030\012\025\021\014\022\107\001\002\000" +
    "\020\003\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb\012\ufffb" +
    "\021\ufffb\001\002\000\012\010\uffef\012\uffef\021\uffef\022" +
    "\uffef\001\002\000\004\016\100\001\002\000\004\023\077" +
    "\001\002\000\014\010\uffee\011\uffee\012\uffee\021\uffee\022" +
    "\uffee\001\002\000\006\003\033\017\034\001\002\000\004" +
    "\012\ufff1\001\002\000\004\012\ufff2\001\002\000\004\021" +
    "\074\001\002\000\010\012\035\013\036\017\041\001\002" +
    "\000\014\003\uffdd\014\uffdd\015\uffdd\020\uffdd\023\uffdd\001" +
    "\002\000\014\003\uffdc\014\uffdc\015\uffdc\020\uffdc\023\uffdc" +
    "\001\002\000\014\003\uffe0\014\uffe0\015\uffe0\020\uffe0\023" +
    "\uffe0\001\002\000\012\003\052\014\046\015\047\020\051" +
    "\001\002\000\010\012\035\013\036\017\041\001\002\000" +
    "\012\003\044\014\046\015\047\020\043\001\002\000\014" +
    "\003\uffdb\014\uffdb\015\uffdb\020\uffdb\023\uffdb\001\002\000" +
    "\014\003\uffda\014\uffda\015\uffda\020\uffda\023\uffda\001\002" +
    "\000\010\012\035\013\036\017\041\001\002\000\010\012" +
    "\uffdf\013\uffdf\017\uffdf\001\002\000\010\012\uffde\013\uffde" +
    "\017\uffde\001\002\000\014\003\uffe1\014\uffe1\015\uffe1\020" +
    "\uffe1\023\uffe1\001\002\000\004\021\071\001\002\000\004" +
    "\021\053\001\002\000\004\011\056\001\002\000\006\011" +
    "\uffe5\022\uffe5\001\002\000\006\011\056\022\070\001\002" +
    "\000\006\003\060\013\057\001\002\000\006\003\063\025" +
    "\064\001\002\000\004\025\061\001\002\000\010\010\030" +
    "\012\025\021\014\001\002\000\006\011\uffe2\022\uffe2\001" +
    "\002\000\010\010\030\012\025\021\014\001\002\000\010" +
    "\010\030\012\025\021\014\001\002\000\006\011\uffe4\022" +
    "\uffe4\001\002\000\006\011\uffe3\022\uffe3\001\002\000\006" +
    "\011\uffe6\022\uffe6\001\002\000\014\010\uffe8\011\uffe8\012" +
    "\uffe8\021\uffe8\022\uffe8\001\002\000\004\011\056\001\002" +
    "\000\006\011\056\022\073\001\002\000\014\010\uffe9\011" +
    "\uffe9\012\uffe9\021\uffe9\022\uffe9\001\002\000\004\011\056" +
    "\001\002\000\006\011\056\022\076\001\002\000\014\010" +
    "\uffe7\011\uffe7\012\uffe7\021\uffe7\022\uffe7\001\002\000\020" +
    "\003\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa\012\ufffa\021" +
    "\ufffa\001\002\000\012\003\101\012\035\013\036\017\041" +
    "\001\002\000\004\023\105\001\002\000\012\003\104\014" +
    "\046\015\047\023\103\001\002\000\014\010\uffed\011\uffed" +
    "\012\uffed\021\uffed\022\uffed\001\002\000\014\010\uffec\011" +
    "\uffec\012\uffec\021\uffec\022\uffec\001\002\000\014\010\uffeb" +
    "\011\uffeb\012\uffeb\021\uffeb\022\uffeb\001\002\000\012\010" +
    "\ufff0\012\ufff0\021\ufff0\022\ufff0\001\002\000\016\002\ufffc" +
    "\010\ufffc\011\ufffc\012\ufffc\021\ufffc\022\ufffc\001\002\000" +
    "\010\003\ufff6\023\ufff6\024\ufff6\001\002\000\010\003\114" +
    "\023\113\024\112\001\002\000\006\003\116\012\115\001" +
    "\002\000\020\003\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8" +
    "\012\ufff8\021\ufff8\001\002\000\020\003\ufff7\005\ufff7\006" +
    "\ufff7\007\ufff7\010\ufff7\012\ufff7\021\ufff7\001\002\000\010" +
    "\003\ufff5\023\ufff5\024\ufff5\001\002\000\010\003\ufff4\023" +
    "\ufff4\024\ufff4\001\002\000\004\002\000\001\002\000\004" +
    "\002\ufffe\001\002\000\004\002\ufffd\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\004\003\003\001\001\000\002\001\001\000" +
    "\004\004\120\001\001\000\002\001\001\000\004\004\117" +
    "\001\001\000\002\001\001\000\004\004\116\001\001\000" +
    "\002\001\001\000\004\004\014\001\001\000\004\005\015" +
    "\001\001\000\002\001\001\000\016\004\020\006\022\007" +
    "\016\011\021\012\023\013\026\001\001\000\004\010\110" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\020\012\105\013\026\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\016\037\017\036\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\044\001\001\000\006\016\041\017\036\001\001\000" +
    "\004\020\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\054\015\053\001\001\000\002\001\001\000" +
    "\004\015\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\004\020\012\061\013\026\001" +
    "\001\000\002\001\001\000\010\004\020\012\065\013\026" +
    "\001\001\000\010\004\020\012\064\013\026\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\071\015\053\001\001\000\004\015" +
    "\066\001\001\000\002\001\001\000\006\014\074\015\053" +
    "\001\001\000\004\015\066\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\016\101\017\036\001\001\000\002" +
    "\001\001\000\004\020\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



   public int errNo = 0;
   
   public static void main( String[] args )
   {
      try
      {
         FileReader file = new FileReader( args[0] );
         MPLexer scanner = new MPLexer( file );
         MPParser parser = new MPParser( scanner );
         parser.parse();
         if ( parser.errNo == 0 )
            System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
         else
            System.out.println( "Analiza zavrsena. Broj gresaka: " + parser.errNo );
      }
      catch( Exception e )
      {
         e.printStackTrace();
      }
   }
   
   public void syntax_error(Symbol cur_token) { }
   
   public void report_error(String message, Object info)
   {
        System.out.print( message );
   }

   public int getLine() {
      return ((MPLexer) getScanner()).getLine();
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Term ::= LPAREN Expression error 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nezatvorena zagrada u izrazu."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Term ::= LPAREN Expression RPAREN 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Term ::= CONST 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Term ::= ID 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // AddOperator ::= MINUS 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*AddOperator*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // AddOperator ::= PLUS 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*AddOperator*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Expression ::= Term 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Expression ::= Expression AddOperator Term 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // WhenStatement ::= WHEN error COLON Statement 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Neispravna konstanta u 'when' uslovu."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*WhenStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // WhenStatement ::= WHEN CONST error Statement 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ':' nakon 'when' konstante."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*WhenStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // WhenStatement ::= WHEN CONST COLON Statement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*WhenStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // WhenStatementList ::= WhenStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*WhenStatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // WhenStatementList ::= WhenStatementList WhenStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*WhenStatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // CaseStatement ::= CASE error LBRACE WhenStatementList RBRACE 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Neispravan uslov u case naredbi."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*CaseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // CaseStatement ::= CASE LPAREN Expression error LBRACE WhenStatementList RBRACE 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ')' u case naredbi."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*CaseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // CaseStatement ::= CASE LPAREN Expression RPAREN LBRACE WhenStatementList RBRACE 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*CaseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Statement ::= Block 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Statement ::= ID ASSIGN error SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Neispravan izraz u dodeli."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Statement ::= ID ASSIGN Expression error 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ';' na kraju naredbe dodele."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Statement ::= CaseStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // StatementList ::= Statement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= FLOAT 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Type ::= CHAR 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NameList ::= NameList COMMA error 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje identifikator nakon zareza."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NameList ::= NameList COMMA ID 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NameList ::= ID 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VarDecl ::= Type NameList error 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ';' nakon deklaracije."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VarDecl ::= Type NameList SEMICOLON 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Declarations ::= 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declarations ::= Declarations error SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Neispravna deklaracija promenljive."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Declarations ::= Declarations VarDecl 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Block ::= LBRACE Declarations StatementList RBRACE 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= error Block 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Program mora poceti sa 'main'."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= MAIN error Block 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaju zagrade () kod main."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= MAIN LPAREN error RPAREN Block 
            {
              Object RESULT = null;
		 System.out.println("Greska u liniji " + parser.getLine() + ": Losi argumenti main funkcije."); parser.errNo++; 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= MAIN LPAREN RPAREN Block 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

